#Configuration file for model training and application.

# seed for the random number generators, to make things reproducible
seed: 0

separator:
    #the classifier to use
    classifier : |
      ensemble.RandomForestClassifier(
          n_estimators=80,
          max_features='sqrt',
          n_jobs=-1,
          max_depth=20,
          criterion='entropy',
      )


    # randomly sample the data if you dont want to use the whole set
    # n_background: 100000
    n_signal: 100000

    # define the number of cross validations to perform
    n_cross_validations : 5

    # Define the name of the category you want to find. The default is 'gamma'.
    # It will be written as <class_name>_prediction into the file when applying the model.
    class_name: dataness

    # Define the name of the column that contains the name of the telescope in case you're working
    # with mulitple telescopes and telescope types
    #telescope_type_key: telescope:name


    features:
      # - clusters
      - kurtosis_long
      - kurtosis_trans
      - skewness_long
      - skewness_trans
      - length
      - size
      - width
        # - cluster_size_ratio
      - n_pixel
