size:
        yscale: log
        transform: np.log10
        xlabel: $\log_{10}(\mathrm{size})$

gamma_energy_prediction:
        yscale: log
        transform: np.log10
        xlabel: $\log_{10}(E_\mathrm{est} / \mathrm{GeV})$

disp_prediction:
        transform: np.abs

cluster_size_ratio:
        yscale: log

delta:
        transform: np.rad2deg
